### ISSUE TITLE
Can't check out repo on windows machine

### ISSUE THREAD

**Issue by katomm** [cardano-foundation/cardano-org#119]
I was just informed that you can't check out the repo under windows because of the file name static/img/dotted-icons/*README.md.

**Comment by RayTracedObserver** [comment]
Oh... Is it because of the * ? Why would it cause such a problem ?

**Comment by katomm** [comment]
On Windows file names must not contain colons, question marks or the asterisk symbol (*). 

Btw this issue was not addressed to you.

**Comment by RayTracedObserver** [comment]
Yes I know it wasn't addressed to me, I just happened to see it and felt slightly responsible. Ah the joys of computing where a single character can wreak havoc :) @katomm
